version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

goos: linux
goarch: amd64
main: ./server/server.go
binary: gocowsay-{{ .Os }}-{{ .Arch }}
ldflags:
  - -s {{ .Env.VERSION_LDFLAGS }}